import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import {Toaster} from "@/components/ui/toaster";
import Header from "@/components/header";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Moneti - The best way to manage webflow monetization",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" className="dark">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <Header/>
            {children}
            <Toaster/>
        </body>
        </html>
    );
}
